apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      annotations:
        co.elastic.logs/enabled: "true"
        co.elastic.logs/json.keys_under_root: "true"
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: jithendar/cart:10.5
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "redis-master"
            - name: CATALOGUE_HOST
              value: "catalogue"
            - name: CATALOGUE_PORT
              value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080